### ISSUE TITLE
Add custom GSWRX theme 

### ISSUE THREAD

**Issue by JoeyyT** [gswrx/angular-material-frontend-boilerplate#4]
Create a custom theme that can be used for GSWRX internal applications to ensure consistency.

https://material.angular.io/guide/theming
https://material.io/design/color/#color-theme-creation

**Comment by JoeyyT** [comment]
open source boiler plate might not need such a thing*

**Comment by christianversloot** [comment]
Maybe it is wise to add it anyway, to show people how to add themes. Although yes indeed, this open source boilerplate might not need such a thing, it doesn't really harm yet helps other people forward.

**Comment by JoeyyT** [comment]
Added in pull request #5
